# Fast Image JEPA (VICReg) Training Configuration
# Smallest and fastest setup for quick execution on CIFAR-10

meta:
  seed: 42
  device: auto

data:
  dataset: cifar10
  batch_size: 512
  num_workers: 8

model:
  type: resnet
  use_projector: true
  proj_hidden_dim: 128
  proj_output_dim: 128

loss:
  type: vicreg
  std_coeff: 1.0
  cov_coeff: 1.0

optim:
  epochs: 5
  lr: 0.1
  weight_decay: 1.0e-4
  warmup_epochs: 1
  warmup_start_lr: 3.0e-5
  min_lr: 0.0

logging:
  log_wandb: false
  log_every: 1
  save_every: 10
  tqdm_silent: false

training:
  use_amp: true
  dtype: float16
