# Rapid Experiment Configuration (Image JEPA / VICReg)
# Optimized for maximum learning progress in ~10-12 minutes on RTX 4090

meta:
  seed: 42
  device: auto

data:
  dataset: cifar10
  batch_size: 3072       # Optimal batch size for RTX 4090 found in search
  num_workers: 16       # Maximize CPU-to-GPU memory transfer

model:
  type: resnet
  use_projector: true
  proj_hidden_dim: 4096 # Wider projector = faster feature decorrelation per epoch
  proj_output_dim: 4096 

loss:
  type: vicreg
  std_coeff: 25.0
  cov_coeff: 1.0

optim:
  epochs: 50            # 50 Epochs takes ~11 minutes total
  lr: 0.707               # Best learning rate found in search for rapid training
  weight_decay: 1.0e-4
  warmup_epochs: 5      # Quick 5-epoch warmup to stabilize the aggressive LR
  warmup_start_lr: 3.0e-5
  min_lr: 0.0

logging:
  log_wandb: false
  log_every: 5          # Less frequent logging saves IO time
  save_every: 50
  tqdm_silent: false

training:
  use_amp: true
  dtype: bfloat16       # bfloat16 hardware acceleration on RTX 4000 series
