logging:
  log_wandb: true
  wandb_group:
  wandb_sweep:
  log_every: 10
  exp_suffix: 11-4
  save_every_n_epochs: 1
  tqdm_silent: true
meta:
  quick_debug: false
  plan_eval_only_mode: false
  light_eval_only_mode: false
  ckpt_dir: checkpoints
  model_folder:
    # /checkpoint/amaia/video/basileterv/experiment/eb_jepa/rand_imp_bs384AdamW_2nd_loss_sweep/impala_encskTrue_prskTrue_cov8_std16_simt12_idm1_spFalse_useprojFalse_idmprojFalse_simtprojFalse_1sttFalse_rolllast_dstc32_henc32_hpre32_lr0.001_wd1e-05_bs384_samplen17_size100000_cw0.35_wb0.0_duptraj0.0_fixwFalse_10-30_seed1
  load_model: true
  load_checkpoint: # e-9.pth.tar
  enable_plan_eval: true
  eval_every_itr: -1
  light_eval_freq: 50
  start_probing_after: 0
  seed: 1
data:
  env_name: two_rooms
  action_noise: 1
  action_angle_noise: 0.2
  action_step_mean: 1.0
  action_step_std: 0.4
  action_lower_bd: 0.2
  action_upper_bd: 1.8
  batch_size: 384
  device: cpu
  dot_std: 1.3
  border_wall_loc: 5
  fix_wall_batch_k:
  fix_wall: false # false to randomize both wall and door loc
  fix_door_location: 18
  fix_wall_location: 32
  exclude_wall_train: ''
  exclude_door_train: ''
  only_wall_val: ''
  only_door_val: ''
  wall_padding: 20
  door_padding: 10
  wall_width: 3
  door_space: 4
  num_train_layouts: -1
  cross_wall_rate: 0.35
  dup_traj_rate: 0.
  expert_cross_wall_rate: 0
  wall_bump_rate: 0.0
  img_size: 65
  max_step: 1
  sample_length: 17 # 17 in PLDM | 90 to eval long rollout
  n_steps: 91
  n_steps_reduce_factor: 1
  size: 100000
  val_size: 10000
  train: true
  repeat_actions: 1
  normalize: true
  # new
  num_workers: 16
  pin_mem: true
  persistent_workers: true
  dtype: bfloat16
model:
  compile: true
  dobs: 2
  henc: 32
  hpre: 32
  dstc: 32
  nsteps: 8
  encoder_architecture: impala # impala | resnet | conv
  train_rollout: last # last | all
  encoder_skip_connections: True
  predictor_skip_connections: True
  regularizer:
    cov_coeff: 8
    std_coeff: 16 # 4.0
    sim_coeff_t: 12 # 0.75 in PLDM
    idm_coeff: 1
    first_t_only: False
    spatial_as_samples: false
    use_proj: false
    idm_after_proj: false
    sim_t_after_proj: false
optim:
  epochs: 12
  lr: 0.001
  grad_clip_enc: 2.0
  grad_clip_pred: 2.0
  weight_decay: 1.e-5
eval:
  plan_cfg_path: examples/ac_video_jepa/cfgs/planning_mppi.yaml # eb_jepa/planning_mppi.yaml
  eval_cfg_path: examples/ac_video_jepa/cfgs/eval.yaml
