name: Lint (Common Code)

on:
  push:
    branches:
      - main
    paths:
      - 'eb_jepa/**'
      - 'examples/**'
      - 'tests/'
  pull_request:
    branches:
      - main
    paths:
      - 'eb_jepa/**'
      - 'examples/**'
      - 'tests/' 

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Set lint paths
        run: echo "lint_paths=eb_jepa examples tests" >> "$GITHUB_ENV"
      - name: Run isort
        run: |
          uv run python -m isort $lint_paths --check 
      - name: Run black
        if: always()
        run: |
          uv run python -m black --check $lint_paths
